[tools]
rust = "latest"

"cargo:cargo-nextest" = "latest"
"cargo:cargo-release" = "latest"
"cargo:cargo-watch" = "latest"
"cargo:git-cliff" = "latest"
"cargo:sccache" = "latest"
"cargo:taplo-cli" = "latest"
"cargo:typos-cli" = "latest"

node = "latest"

"npm:browser-sync" = "latest"
"npm:markdownlint" = "latest"
"npm:prettier" = "latest"
"npm:typescript" = "latest"

python = "latest"
