max_width = 80
newline_style = "Unix"
reorder_imports = true
style_edition = "2024"
tab_spaces = 2

format_macro_bodies = true
format_macro_matchers = true
imports_granularity = "Item"
unstable_features = true
