style_edition = "2024"
tab_spaces = 2
newline_style = "Unix"
reorder_imports = true
max_width = 80

unstable_features = true
imports_granularity = "Item"
format_macro_matchers = true
format_macro_bodies = true
