[default]
extend-ignore-re = [
  # Ignore blocks with `// spellchecker:<on|off>`
  "(?s)(#|//)\\s*spellchecker:off.*?\\n\\s*(#|//)\\s*spellchecker:on",
]

extend-ignore-words-re = [
  # Ignore specific words
]

[files]
extend-exclude = ["CHANGELOG.md", "dev.py"]
