allow-branch = ["main"]
pre-release-hook = [
  "git-cliff",
  "-o",
  "RSVIM_CLI_CHANGELOG.md",
  "--tag",
  "{{version}}",
]
shared-version = true
tag = false
tag-message = "chore(release): {{version}}"
