# Default Rsvim ColorScheme

[syn]
attribute = "white"
boolean = "magenta"
comment = "grey"
constant = "red"
constructor = "cyan"
embedded = "cyan"
error = "red"
function = "green"
keyword = "yellow"
module = "red"
number = "red"
operator = "yellow"
property = "cyan"

[ui]
foreground = "white"
background = "black"
