name: API Docs
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
permissions:
  contents: write
  packages: write
  id-token: write
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
jobs:
  typedoc:
    name: Typedoc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Generate Docs
        run: |
          echo "show PWD"
          echo $PWD
          echo "ls -la"
          ls -la
          echo "npm install"
          npm install
          echo "npm run typedoc"
          npm run typedoc
          echo "tree generated-typedocs"
          tree generated-typedocs
          echo "cp -rf generated-typedocs to $HOME/.generated-typedocs"
          cp -rf generated-typedocs $HOME/.generated-typedocs
      - name: Send PR to rsvim.github.io
        run: |
          echo "show PWD"
          echo $PWD
          echo "ls -la"
          ls -la

          REPOSITORY="rsvim/rsvim.github.io"
          FOLDER="$HOME/.repo/$REPOSITORY"
          COMMIT_ID="${GITHUB_SHA::7}"
          BRANCH_NAME="generate_typedoc"
          GENERATED_FOLDER="$HOME/.generated-typedocs"
          TOKEN="$HOME/.token.txt"
          echo "var REPOSITORY"
          echo $REPOSITORY
          echo "var FOLDER"
          echo $FOLDER
          echo "var COMMIT_ID"
          echo $COMMIT_ID
          echo "var BRANCH_NAME"
          echo $BRANCH_NAME
          echo "var GENERATED_FOLDER"
          echo $GENERATED_FOLDER

          echo "git clone"
          git clone --depth=1 --branch=main https://github.com/$REPOSITORY $FOLDER
          git remote set-url origin https://x-access-token:${{ secrets.GENDOC_TOKEN }}@github.com/$GITHUB_REPOSITORY
          cd $FOLDER
          git config --global user.email "rsvim-auto-bot@users.noreply.github.com"
          git config --global user.name "Rsvim AutoBot"

          echo "git checkout -b ${BRANCH_NAME}"
          git checkout -b $BRANCH_NAME

          echo "remove 10__global, 50__rsvim"
          rm -rf ./docs/api_references/10__global
          rm -rf ./docs/api_references/50__rsvim

          echo "cp 10_global, 50__rsvim to rsvim.github.io"
          cp -rf $GENERATED_FOLDER/10__global ./docs/api_references/10__global
          cp -rf $GENERATED_FOLDER/50__rsvim ./docs/api_references/50__rsvim

          git add -A --verbose
          git commit -m "chore: Auto generate APIs on ${COMMIT_ID}"
          echo "git push origin ${BRANCH_NAME}"
          git push --force origin $BRANCH_NAME

          echo "${{ secrets.GENDOC_TOKEN }}" > $HOME/.token.txt
          gh auth login --with-token < $HOME/.token.txt
          echo "gh pr create"
          gh pr create --label "generate api" --title "chore(api): Generate APIs on ${COMMIT_ID}" --body "" --head "${BRANCH_NAME}" --base "main"
