name: Optional
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  CARGO_NET_RETRY: 3
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"
  RSVIM_LOG: "trace"
  RUST_BACKTRACE: "full"
  SCCACHE_DIR: .cache/sccache
jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: amannn/action-semantic-pull-request@v6
        if: ${{ github.ref != 'refs/heads/main' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: crate-ci/typos@master
      - name: Prettier
        run: |
          npm install -g prettier
          prettier --version
          echo "show PWD=${PWD}"
          echo "prettier --check *.md **/*.ts"
          prettier --check *.md **/*.ts
  bloaty:
    name: Bloaty
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request }}
    env:
      RUSTC_WRAPPER: "sccache"
      SCCACHE_GHA_ENABLED: "false"
    steps:
      - uses: Swatinem/rust-cache@v2
        with:
          cache-directories: $SCCACHE_DIR
      - uses: mozilla-actions/sccache-action@v0.0.9
      - name: Install Rust
        run: |
          rustup update --no-self-update stable
          rustup default stable
          rustup component add --toolchain stable rust-src clippy
      - name: Check out 'current' branch
        uses: actions/checkout@v5
        with:
          fetch-depth: '0'
      - name: Build 'current' branch
        run: cargo build --release
      - name: Save 'current' branch binary
        run: cp ./target/release/rsvim ./target/release/original.elf
      - name: Run Bloaty on 'current' branch
        uses: carlosperate/bloaty-action@v1
        id: bloaty-step
        with:
          bloaty-args: ./target/release/rsvim
          output-to-summary: true
      - name: Checkout 'main' branch
        run: git checkout ${{ github.event.pull_request.base.sha }}
      - name: Rebuild 'main' branch
        run: cargo build --release
      - name: Run Bloaty to compare both output files
        id: bloaty-comparison
        uses: carlosperate/bloaty-action@v1
        with:
          bloaty-args: ./target/release/original.elf -- ./target/release/rsvim
          output-to-summary: true
    # - name: Add a PR comment with summary and diff
    #   continue-on-error: true
    #   uses: actions/github-script@v6
    #   with:
    #     script: |
    #       github.rest.issues.createComment({
    #         issue_number: context.issue.number,
    #         owner: context.repo.owner,
    #         repo: context.repo.repo,
    #         body: '## Bloaty output\n```\n${{ steps.bloaty-step.outputs.bloaty-output-encoded }}```\n## PR build size diff\n```\n${{ steps.bloaty-comparison.outputs.bloaty-output-encoded }}```\n'
    #       })
